fix(checkver): fix output with '-Version'
ScoopInstaller/Scoop pull request #3774
Opened 2019-11-29 10:52 UTC by niheaven

Before

![wrong](https://user-images.githubusercontent.com/5832170/69863875-cb397e00-12d8-11ea-9d4b-08619b04da40.png)

After

![right](https://user-images.githubusercontent.com/5832170/69864141-4c911080-12d9-11ea-8675-a6c1f66d858c.png)

2019-12-02 09:31 UTC, Ash258 commented
If I can see correctly, main changes are:

- https://github.com/lukesampson/scoop/pull/3774/files#diff-6d5ec5a5587d8c2e2cd120423846e581L308-L310
- https://github.com/lukesampson/scoop/pull/3774/files#diff-6d5ec5a5587d8c2e2cd120423846e581R78-R82
- https://github.com/lukesampson/scoop/pull/3774/files#diff-6d5ec5a5587d8c2e2cd120423846e581R202-R206

Rest is just messy compare due to nested `if (!$ver) {`, which was not changed right?

2019-12-02 12:26 UTC, r15ch13 commented
The same logic could be archived without the indentation by adding the check for `$Version` later.


Change
---
https://github.com/lukesampson/scoop/blob/a9fa775d59b14e7dce335313faa0eff855469764/bin/checkver.ps1#L274-L280

To
---
```pwsh
    if (!$ver) {
        next "couldn't find new version in $url"
        continue
    }

    if($Version) {
        $expected_ver = $ver
        $ver = $Version
    }

    # Skip actual only if versions are same and there is no -f
    if (($ver -eq $expected_ver) -and !$ForceUpdate -and $SkipUpdated) { continue }

```

2019-12-02 14:59 UTC, niheaven commented
@Ash258 Yes, rest is just caused by indenting

@r15ch13 The big `if` just skips time-consuming version finding step.

2022-01-07 15:38 UTC, niheaven commented
Tested after resolve conflicts (merged current 'develop' branch)

2022-01-07 20:05 UTC, rashil2000 requested changes
Will it be possible to isolate indentation changes in a separate commit (in this PR itself)? Otherwise it's difficult to review.

2022-01-07 20:05 UTC, rashil2000 commented on bin/checkver.ps1
> +    Updated manifest to specific version.
```suggestion
    Update manifest to specific version.
```

2022-01-08 07:53 UTC, niheaven commented
Separate into two commits, Part I is just indenting, while Part II is fixed code.

2022-01-08 07:54 UTC, Ash258 commented
<img width="148" alt="image" src="https://user-images.githubusercontent.com/13260377/148636655-e49d2cc0-4c31-4b99-9233-6d951af17ad3.png">

2022-01-08 08:00 UTC, niheaven commented
> <img alt="image" width="148" src="https://user-images.githubusercontent.com/13260377/148636655-e49d2cc0-4c31-4b99-9233-6d951af17ad3.png">

Wonderful feature that I never found in GitHub.

2022-01-08 08:05 UTC, rashil2000 commented
> <img alt="image" width="148" src="https://user-images.githubusercontent.com/13260377/148636655-e49d2cc0-4c31-4b99-9233-6d951af17ad3.png">

Right, completely forgot about this 😅

2022-01-08 08:08 UTC, rashil2000 approved these changes

2022-01-08 08:09 UTC, merged