fix(core): use Get-Encoding to set webclient encoding
ScoopInstaller/Scoop pull request #4956
Opened 2022-05-28 12:27 UTC by yi-Xu-0100

Add Get-Encoding function in core.ps1

#### Description

#### Motivation and Context

close #4911 #4324

Relates to #4911 #4324

#### How Has This Been Tested?

#### Checklist:

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).
- [x] I have ensured that I am targeting the `develop` branch.
- [x] I have updated the documentation accordingly.
- [x] I have updated the tests accordingly.
- [ ] I have added an entry in the CHANGELOG.

2022-06-02 00:16 UTC, yi-Xu-0100 commented
@rashil2000 Any review here will be helpful~ 😁

2022-06-02 15:37 UTC, niheaven requested changes

2022-06-02 15:37 UTC, niheaven commented on lib/core.ps1
> +function Get-Encoding($url) {
Pass `$wc` in the function

2022-06-02 15:37 UTC, niheaven commented on lib/manifest.ps1
>  function manifest_path($app, $bucket) {
```suggestion
function manifest_path($app, $bucket) {
```

2022-06-02 15:37 UTC, niheaven commented on libexec/scoop-virustotal.ps1
>  . "$PSScriptRoot\..\lib\getopt.ps1"
```suggestion
. "$PSScriptRoot\..\lib\getopt.ps1"
```

2022-06-04 15:58 UTC, niheaven commented
Do you have some testing manifests?

2022-06-05 00:36 UTC, yi-Xu-0100 commented
@niheaven ,Thanks for your reply. 😁

In https://github.com/ScoopInstaller/Scoop/issues/4911#issue-1229175577 , I use 

```powershell
scoop install "https://raw.githubusercontent.com/ygguorun/scoop-bucket/master/bucket/PDFPatcher.json"
```

, and [this manifest - DoveBoy/Apps/pdfpatcher](https://raw.githubusercontent.com/DoveBoy/Apps/master/bucket/pdfpatcher.json) has the `checkver`, and they all work well.

2022-06-06 09:02 UTC, niheaven commented
`checkver` has some error, could you please check it again?

2022-06-08 11:37 UTC, yi-Xu-0100 commented
@niheaven  I used it for `scoop update` and `scoop install`, they all work well. 

Could you please provider the way to test the `checkver`, I have no idea for it.🤔

2022-06-09 10:40 UTC, niheaven commented
Checkout this branch and cd in any bucket, run `.\bin\checkver.ps1 xxx`, there are some bugs :)

2022-06-09 13:56 UTC, yi-Xu-0100 commented
@niheaven Thanks for pointing out the problem, I think it's fixed now. 😁

2022-06-10 15:36 UTC, niheaven approved these changes

2022-06-11 02:34 UTC, yi-Xu-0100 commented
@niheaven Thanks for adding the judgment for null values, but there is something we need to revert.

If we use `(Get-Encoding($wc)).GetString($wc.DownloadData($url))`, then `(Get-Encoding($wc))` can only get the return result in UTF-8, because The `ResponseHeaders` of `$wc` will be `$null` before the data is downloaded. 

So I re-split the expression to handle the case where `charset` is something else.

2022-06-12 14:00 UTC, niheaven commented
Aha, right?

Okay, I'll test it tomorrow and it seems stable enough now.

2022-06-13 15:20 UTC, niheaven approved these changes

2022-06-13 15:21 UTC, merged