refactor: rename `dl` to `Invoke-WebDownload`
ScoopInstaller/Scoop pull request #5143
Opened 2022-09-12 20:34 UTC by examosa

#### Description

This PR renames the `dl` and related functions to use more descriptive names that better adhere to PowerShell conventions.

#### Motivation and Context

Addresses #3830

#### How Has This Been Tested?

Test suite run on local machine and in [CI](https://github.com/examosa/Scoop/actions/runs/3040324142/jobs/4896244634); all remain passing.

#### Checklist:

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).
- [x] I have ensured that I am targeting the `develop` branch.
- [x] I have updated the documentation accordingly.
- [x] I have updated the tests accordingly.
- [x] I have added an entry in the CHANGELOG.

2022-09-13 10:02 UTC, rashil2000 commented
I think `Invoke-Download` is good enough (`web` is implied)

2022-09-13 10:22 UTC, niheaven requested changes

2022-09-13 10:22 UTC, niheaven commented on bin/install.ps1
> +$zipUrl = "https://github.com/ScoopInstaller/Scoop/archive/master.zip"
```suggestion
$zipUrl = 'https://github.com/ScoopInstaller/Scoop/archive/master.zip'
```

2022-09-13 10:22 UTC, niheaven commented on bin/install.ps1
> +$zipUrl = "https://github.com/ScoopInstaller/Main/archive/master.zip"
```suggestion
$zipUrl = 'https://github.com/ScoopInstaller/Main/archive/master.zip'
```

2022-09-13 10:22 UTC, niheaven commented on lib/install.ps1
> +    $fname = Import-Url $app $version $manifest $bucket $architecture $dir $use_cache $check_hash
```suggestion
    $fname = Invoke-ScoopDownload $app $version $manifest $bucket $architecture $dir $use_cache $check_hash
```

2022-09-13 14:22 UTC, examosa commented
Thanks for the feedback @niheaven. I have a few clarifying questions:

1. It looks like you're suggesting to remove `Invoke-WebDownload` and use `Invoke-WebRequest` directly. Will it be alright to omit the headers from the original code and the `-UseBasicParsing` flag ([PowerShell 5 compatibility](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/invoke-webrequest?view=powershell-5.1#:~:text=By%20default%2C%20script%20code%20in%20the%20web%20page%20may%20be%20run%20when%20the%20page%20is%20being%20parsed%20to%20populate%20the%20ParsedHtml%20property.%20Use%20the%20%2DUseBasicParsing%20switch%20to%20suppress%20this.))?
2. Based on the suggested changes to string quotes, would it be alright if I updated the VS Code workspace settings like so?

```patch
@@ -4,6 +4,7 @@
     "powershell.codeFormatting.preset": "OTBS",
     "powershell.codeFormatting.alignPropertyValuePairs": true,
     "powershell.codeFormatting.ignoreOneLineBlock": true,
+    "powershell.codeFormatting.useConstantStrings": true,
     "files.exclude": {
         "**/.git": true,
         "**/.svn": true,
```

2022-09-14 03:02 UTC, niheaven commented
> 1. It looks like you're suggesting to remove `Invoke-WebDownload` and use `Invoke-WebRequest` directly. Will it be alright to omit the headers from the original code and the `-UseBasicParsing` flag ([PowerShell 5 compatibility](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/invoke-webrequest?view=powershell-5.1#:~:text=By%20default%2C%20script%20code%20in%20the%20web%20page%20may%20be%20run%20when%20the%20page%20is%20being%20parsed%20to%20populate%20the%20ParsedHtml%20property.%20Use%20the%20%2DUseBasicParsing%20switch%20to%20suppress%20this.))?

Yes, it should, but in fact this file is no longer used. Now installer script is [here](https://github.com/ScoopInstaller/Install/blob/master/install.ps1) in https://github.com/ScoopInstaller/Install.

> 2. Based on the suggested changes to string quotes, would it be alright if I updated the VS Code workspace settings like so?
> 
> ```diff
> @@ -4,6 +4,7 @@
>      "powershell.codeFormatting.preset": "OTBS",
>      "powershell.codeFormatting.alignPropertyValuePairs": true,
>      "powershell.codeFormatting.ignoreOneLineBlock": true,
> +    "powershell.codeFormatting.useConstantStrings": true,
>      "files.exclude": {
>          "**/.git": true,
>          "**/.svn": true,
> ```

Yes, it is, and we usually use the following setting too:

```json
"powershell.codeFormatting.useCorrectCasing": true
```

2022-09-16 02:29 UTC, niheaven approved these changes

2022-09-16 02:36 UTC, merged

2022-09-24 16:13 UTC, rashil2000 commented
@examosa Can you make a corresponding PR to [GithubActions](https://github.com/ScoopInstaller/GithubActions) too? Otherwise the actions will break when this feature gets released.